### ISSUE TITLE
Set up new site to explain that WPisNotWP.com is not WP.org

### ISSUE THREAD

**Issue by lucyllewy** [casparhubinger/wpisnotwp.com#1]
While I applaud the effort to explain to the public of the differences between WordPress and WordPress.com, I feel that the Site WPisNotWP.com could be confused as a WordPress.org initiative. I therefore think it would be advisable to set up an informational website to explain that "WordPress is not WordPress.com" is not sponsored or endorsed by WordPress.org. Perhaps the domain WPisNotWP.comIsNotWP.org would be useful?

P.S. This was a humorous issue tracker interlude. Your regular issue tracker programming will resume shortly.

**Comment by glueckpress** [comment]
Good catch! 😉 

Humour aside, I believe this repository fulfils the purpose. As of iteration [1.0.2](https://github.com/glueckpress/wpistnotwp.com/releases/tag/1.0.2) the _Whois_ link in the [footer of the website](https://wpisnotwp.com/#colophon) points to this repo. 

The [README](https://github.com/glueckpress/wpistnotwp.com#is-this-a-community-project) file of this repo then states:
> [The website] definitely is not part of the WordPress.org or WordPress.com platforms.

It is not uncommon to place meta information on a separate page than an actual landing page. Usually an unobtrusive link to the separate page is considered sufficient. 

As an example, look at [this page](https://automattic.com/press/brand-materials/) listing brand material of a company of international renown.

When you scroll to the bottom, you’ll see a familiar brand that is known to be owned by an entirely different entity than the company whose brand material page you’re looking at:

<img width="955" alt="A8c brand material page listing “WordPress” next to company brands" src="https://user-images.githubusercontent.com/308422/29437613-e6617a9c-83b1-11e7-8ee4-5a91d5501c67.png">

You may or may not notice that the download link below the third party brand points to another website. In a recent discussion online, this was [considered a sufficient solution](https://twitter.com/hlashbrooke/status/885413635325132800):
Apparently, visitors are supposed to be able to differentiate between company brands and third party brand just based on the text of an unobtrusive download link with low colour contrast ratio. 

I believe we’re doing way better here already. 😉
