### ISSUE TITLE
Adding languages

### ISSUE THREAD

**Issue by glueckpress** [casparhubinger/wpisnotwp.com#3]
Currently, there are 2 requests to add Chinese (Taiwan) and Portuguese translations to this website. While I see no issues with adding languages in general, I’d appreciate feedback for the infamous decision:

## Subdomains or sub-directories?

i.e.: `{locale}.wpistnotwp.com` or `wpistnotwp.com/{locale}/`?

Since this website is and always will be plain static HTML, there are no technical implications here. Subdomains are free on my account, so we can add as many as we wish.

The question is: Which is nicer to use and easier to remember, a subdomain or a sub-directory?

I’ve looked around for examples:

### A. WordPress.org

```
tw.wordpress.org – Chinese (Taiwan)
cn.wordpress.org – Chinese (China)
pt.wordpress.org – Portuguese (Portugal)
br.wordpress.org – Portuguese (Brazil)
ru.wordpress.org – Russian (no variant)

```

### B. WordPress.com

```
zh-tw.wordpress.com – Chinese (Taiwan)
zh-cn.wordpress.com – Chinese (China)
                    – Portuguese (Portugal) not supported
br.wordpress.com    – Portuguese (Brazil)
ru.wordpress.com    – Russian (no variant)
```

_Apparently it’s the simplified locale code when there is no variant available on the platform, regardless of variants for a locale in general._

### C. Mozilla

```
www.mozilla.org/zh-TW/ – Chinese (Taiwan)
www.mozilla.org/zh-CN/ – Chinese (China)
www.mozilla.org/pt-PT/ – Portuguese (Portugal)
www.mozilla.org/pt-BR/ – Portuguese (Brazil)
www.mozilla.org/ru/    – Russian (no variant)
```

My personal preference goes in direction of B (WordPress.com), but with full locale codes for every locale that could have variants:

```
zh-tw.wpisnotwp.com – Chinese (Taiwan)
zh-cn.wpisnotwp.com – Chinese (China)
pt-pt.wpisnotwp.com – Portuguese (Portugal)
pt-br.wpisnotwp.com – Portuguese (Brazil)
ru.wpisnotwp.com    – Russian (no variant)
```

## Feedback?

I don’t mean to over-engineer this decision, but I’d appreciate feedback from a few people before moving on with an actual implementation.

- Which structure would you prefer: A, or B, or C, or a different one?
- Why?

Thanks!

**Comment by Pseric** [comment]
Hi,

I prefer to use A. WordPress.org URL architecture, which is a Subdomains, on the other hand, wpisnotwp.com and WordPress.org related, it will be more easy to remember.

Thanks!

**Comment by marcoandrei** [comment]
Caster, the option A appears to me to be easier to remember. I agree with Pseric.

**Comment by glueckpress** [comment]
Guys, I appreciate the feedback, and I’d be willing to roll with option A. However, there is one more issue that occurred to me just now: Adding translated versions would affect how the [service worker](https://github.com/glueckpress/wpistnotwp.com/blob/master/sw.js) needs to be set up.

If any of you wants to look into this, feel free to go ahead and add further insight as comments here, or send pull requests. For my part, I won’t have any resources to spend time figuring this out before October.

**Comment by marcoandrei** [comment]
Dear Caspar, sorry for the big delay in this reply. Actually I'm very busy
in these days as well and I couldn't help you in the issue. I think I can
look at this only in November.



--
Marco Andrei Kichalowsky, diretor de marketing
Email: mandrei@arsnova.digital
Fone: (51) 3126-9223
Web: https://www.arsnova.digital


2017-09-03 10:48 GMT-03:00 Caspar Hübinger <notifications@github.com>:

**Comment by glueckpress** [comment]
Closing this for now, see: https://github.com/glueckpress/wpisnotwp.com/pull/2#issuecomment-366630740
